### ISSUE TITLE
How to include in existing ci project ?

### ISSUE THREAD

**Issue by d33pak-s1ngh** [ParitoshVaidya/CodeIgniter-JWT-Sample#1]
can you show the steps how we can add jwt into existing ci project that will be help full.

**Comment by ParitoshVaidya** [comment]
You will need following files:

**/application/config/jwt.php** <= Add **jwt_key** here
**/application/helpers/authorization_helper.php
/application/helpers/jwt_helper.php**

In **/application/config/autoload.php** add 
```
$autoload['helper'] = array('url', 'form', 'jwt', "authorization");
$autoload['config'] = array('jwt');
```

That's it. You are ready. Add your logic to generate token, eg.

```
$tokenData = array();
$tokenData['id'] = 1; //TODO: Replace with data for token
$output['token'] = AUTHORIZATION::generateToken($tokenData);
```

Please reply, if you need additional details. Happy coding!
